# amino_acid: "ARG"
batch_size: 4096
num_workers: 16
torsion_dim: 2
epochs: 500
num_folds: 5
data_path: "dataset/synth/high_energy/data"
decoder: true
mul_HAE: true
energy_path: "dataset/synth/high_energy/energy"
force_types: ["PeriodicTorsionForce", "LJForce", "CoulombForce"]
hidden_dims: "[2048, 512, 256]"
HAE_dim: 0
iqr_filter_energy: False
interpolate_energy: False
normalize_energy: True
inf_filter: False
lr: 0.005
