# amino_acid: "ARG"
batch_size: 4096
num_workers: 16
VAE: false
HAE: true
epochs: 800
name: "HAE"
data_path: "dataset/full/data"
latent_path: "dataset/full/HAE_latents"
energy_path: "dataset/full/interpolated_energy"
force_types: ["PeriodicTorsionForce", "LJForce", "CoulombForce"]
iqr_filter_energy: False
interpolate_energy: False
normalize_energy: True
inf_filter: False
hidden_dims: "[1024, 256, 128]"
latent_dim: 0
lr: 0.002
data_increase: 1
border_ratio: 0.75