amino_acid: "ARG"
batch_size: 4096
num_workers: 0
VAE: false
HAE: false
torsion: true
epochs: 250
data_path: "dataset/clean"
latent_path: "dataset/torsion_latents"
energy_path: "dataset/energy_15k"
hidden_dims: "[1024, 256, 128]"
lr: 0.002